name: Dozer
options:
  usesTabs: false
  tabWidth: 4
  createIntermediateGroups: true
  xcodeVersion: 15.4
  deploymentTarget: 12.0
packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.2.0
  Defaults:
    url: https://github.com/sindresorhus/Defaults
    from: 4.2.2
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin
    from: 4.1.0
  Preferences:
    url: https://github.com/sindresorhus/Preferences
    from: 2.2.1
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.4
targets:
  Dozer:
    type: application
    platform: macOS
    deploymentTarget:
      macOS: 12.0
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
    sources:
      - Dozer
    postBuildScripts:
      - path: Scripts/SignFrameworks.sh
        name: Sign Frameworks
        runOnlyWhenInstalling: true
      - script: |
          if [ -x /opt/homebrew/bin/swiftgen ]; then
            /opt/homebrew/bin/swiftgen
          elif [ -x /usr/local/bin/swiftgen ]; then
            /usr/local/bin/swiftgen
          else
            echo "error: SwiftGen not installed"
            exit 1
          fi
        name: Generate files using SwiftGen
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: Dozer/Other/Dozer.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: "com.mortennn.Dozer"
        SWIFT_VERSION: 5
        DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
        ENABLE_HARDENED_RUNTIME: true
        MACOSX_DEPLOYMENT_TARGET: 12.0
        VERSIONING_SYSTEM: apple-generic
        CURRENT_PROJECT_VERSION: 31
        ARCHS: "arm64 x86_64"
        VALID_ARCHS: "arm64 x86_64"
    dependencies:
      - package: KeyboardShortcuts
      - package: Defaults
      - package: LaunchAtLogin
        product: LaunchAtLogin
      - package: Preferences
        product: Preferences
      - package: Sparkle
        product: Sparkle
  DozerTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget:
      macOS: 12.0
    sources:
      - DozerTests
    settings:
      base:
        MACOSX_DEPLOYMENT_TARGET: 12.0
        SWIFT_VERSION: 5
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Dozer.app/Contents/MacOS/Dozer"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: Dozer
      - package: KeyboardShortcuts
      - package: Defaults

  DozerUITests:
    type: bundle.ui-testing
    platform: macOS
    deploymentTarget:
      macOS: 12.0
    sources:
      - DozerUITests
    settings:
      base:
        MACOSX_DEPLOYMENT_TARGET: 12.0
        SWIFT_VERSION: 5
        TEST_TARGET_NAME: Dozer
    dependencies:
      - target: Dozer

schemes:
  Dozer:
    build:
      targets:
        Dozer: all
        DozerTests: testing
        DozerUITests: testing
    test:
      targets:
        - DozerTests
        - DozerUITests
